steps:
  build_and_deploy:
    image: ruby:latest
    environment:
      CB_TOKEN:
        from_secret: cb_token
    commands:
      - chmod -R a+w .
      - bundle install
      - bundle exec jekyll build
      - cd _site
      - git init
      - git config user.name "Woodpecker"
      - git config user.email "username@noreply.codeberg.org"
      - git add .
      - git commit -m "Deploy from CI"
      - git push -f https://drekunia:$${CB_TOKEN}@codeberg.org/drekunia/pages.git master:pages