# Site settings
title: "drekunia"
description: >-
    Game developer and artist creating games at the intersection of code and arts.
    Let's connect and create.
url: "https://drekunia.github.io"
twitter_username: drekunia
image: /assets/img/og-image.png

# Build settings
markdown: kramdown
highlighter: rouge

# Author info
author:
    name: "drekunia"
    title: "Andre Kurniawan"
    bio:
    avatar: "/assets/img/avatar.webp"

# Social links
links:
    - name: contact/inquiries
      url: mailto:drekunia@gmail.com
      bold: true
      same_tab: true
    # put hidden links on the bottom
    - name: mastodon
      url: https://mastodon.gamedev.place/@drekunia
      hidden: true

# Redirects to Codeberg
plugins:
    - jekyll-redirect-from
new_url: "https://drekunia.codeberg.page"
