# General settings of the site you can find at /_data/settings.yml

url: https://drekunia.com # the base hostname & protocol for your site, e.g. http://example.com
baseurl: '' # the subpath of your site, e.g. /blog

encoding: UTF-8

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: ['_pages']
permalink: /:title

sass:
  sass_dir: _sass
  style: compressed
