# Site settings
title: "drekunia"
description: >-
  Creating games at the intersection of code and arts. Let's connect.
url: "https://drekunia.github.io"
twitter_username: drekunia
image: /assets/img/og-image.png

# Build settings
markdown: kramdown
highlighter: rouge

# Author info
author:
  name: "drekunia"
  title: "Andre Kurniawan"
  bio: >-
    I build creative projects by leveraging 
    [code](https://github.com/drekunia){: target="_blank" rel="noopener noreferrer"} 
    as an art form. 
    Most of my work revolves around technology and design, specifically 
    [game development](https://drekunia.itch.io){: target="_blank" rel="noopener noreferrer"}, 
    [digital art](https://www.artstation.com/drekunia){: target="_blank" rel="noopener noreferrer"}, and 
    [music](https://www.subvert.fm/drekunia){: target="_blank" rel="noopener noreferrer"}. 
    Always looking for exciting new opportunities to learn and collaborate.
  avatar: "/assets/img/avatar.webp"

# Social links
links:
  - name: contact/inquiries
    url: mailto:drekunia@gmail.com
    same_tab: true
  - name: instagram
    url: https://instagram.com/drekunia
  # - name: x/twitter
  #   url: https://x.com/drekunia
  # - name: bluesky
  #   url: https://bsky.app/profile/drekunia.bsky.social
  - name: youtube
    url: https://www.youtube.com/@drekunia
  #   bold: true
  - name: linkedin
    url: https://www.linkedin.com/in/drekunia
  # - name: github
  #   url: https://github.com/drekunia
  # - name: codeberg
  #   url: https://codeberg.org/drekunia
  # - name: itch.io
  #   url: https://drekunia.itch.io/
  # - name: artstation
  #   url: https://www.artstation.com/drekunia
  # - name: bandcamp
  #   url: https://drekunia.bandcamp.com
  # - name: subvert
  #   url: https://www.subvert.fm/drekunia
  - name: blog
    url: https://drekunia.github.io/blog
    same_tab: true
  # put hidden links on the bottom
  - name: mastodon
    url: https://mastodon.gamedev.place/@drekunia
    hidden: true
