---
#-------------------------------
# General Site Settings

title: Andre Kurniawan | Backend Developer
# email-endpoint: https://formspree.io/f/xxxxxxxx

# Here you can add link in main menu
menu:
  - { name: Work, url: 'work', icon: 'ion ion-ios-briefcase' }
  - { name: Blog, url: 'blog', icon: 'ion ion-ios-paper' }
  - { name: Contact, url: 'contact', icon: 'ion ion-ios-mail' }

#-------------------------------
# About Section

avatar: 05.jpg
name: Andre Kurniawan
my-job: Backend Developer
description: Backend developer currently focusing on Go. Experienced with Elixir (Phoenix Framework), PHP (Laravel), PostgreSQL, MySQL, Git, Tailwind CSS, and Wordpress. Also interested in frontend development.
email: drekunia@gmail.com

#-------------------------------
# Skills Section

skills-title: Skills
skills:
  - { name: PHP (Laravel), value: '90' }
  - { name: Elixir (Phoenix), value: '85' }
  - { name: Go, value: '80' }
  - { name: SQL, value: '80' }
  - { name: Wordpress, value: '90' }
  - { name: Git, value: '90' }

#-------------------------------
# Experience Section

experience-title: Experience
experience:
  - {
      company-name: 'PT. Ilmu Data Terpadu',
      duration: May 2020 - May 2021,
      job-position: Full Stack Developer,
      description: 'Responsible for developing Kuponsehat.com, a marketplace for medical services, using Elixir, Phoenix Framework, Tailwind CSS, and PostgreSQL.',
    }

  - {
      company-name: 'Dafunda Media',
      duration: Jun 2019 - May 2020,
      job-position: Web Developer,
      description: 'Responsible for creating news and media websites using Laravel, and also Wordpress custom themes. I also wrote articles in English.',
    }

#-------------------------------
# Education Section

education-title: Education
education:
  - {
      degree: Sanbercode,
      years: 2019,
      organization: Laravel Web Development,
      # description:
    }

  - {
      degree: Universitas Gadjah Mada,
      years: 2014 - 2019,
      organization: Electrical Engineering (Undergraduate Program),
      # description:
    }

#-------------------------------
# Clients Section
# clients-title: Clients
# clients:
#   - {
#       name: 'Dianna Smiley',
#       title: 'Social Media, Co and Co',
#       quote: '<p><strong>Working with Chris was the highlight of my career.</strong> Art party before they sold out lo-fi cronut. Narwhal normcore kinfolk crucifix cronut coloring book man braid lomo fixie sartorial helvetica cornhole activated charcoal ethical.</p>',
#     }

#-------------------------------
# Work Section

projects:
  - { name: Design Talks, image: '10.jpg' }
  - { name: Abstract Page, image: '11.jpg' }
  - { name: Round Shapes, image: '12.jpg' }
  - { name: Color Palette, image: '13.jpg' }
  - { name: Color Palette, image: '14.jpg' }
  - { name: Color Palette, image: '15.jpg' }

#-------------------------------
# Social Settings

social:
  - { link: 'https://linkedin.com/in/drekunia', icon: ion-logo-linkedin }
  - { link: 'https://github.com/drekunia', icon: ion-logo-github }
  - { link: 'https://instagram.com/drekunia', icon: ion-logo-instagram }

# social network icons available (https://ionicons.com/): 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' /

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: drekunia # Add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
