name: Build and Deploy Jekyll
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: https://codeberg.org/actions/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Build Jekyll
        run: |
          bundle install
          bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to Codeberg Pages
        uses: https://codeberg.org/git-pages/action@v1
        with:
          folder: _site